name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: azure/docker-login@v2
      with:
        username: ${{ secrets.AZURECI_USERNAME }}
        password: ${{ secrets.AZURECI_TOKEN }}
        login-server: "srelabcr.azurecr.io"
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: srelabcr.azurecr.io/ipinfo:latest
